
---DDL
--CREATE
CREATE TABLE Alumnos(
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
SEMESTRE INTEGER
);

CREATE TABLE Maestros(
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
);

--DROP
DROP TABLE Maestros;

--ALTER
ALTER TABLE Alumnos ADD CORREO VARCHAR(100);

--TRUCATE
TRUNCATE TABLE Alumnos;

----DML
--INSERT
INSERT Alumnos(NOMBRE,APELLIDO,SEMESTRE) VALUES ('Hugo','Barrios',7);
INSERT Alumnos(NOMBRE,APELLIDO,SEMESTRE) VALUES ('Ernesto','Rosales',7);
SELECT * FROM Alumnos;

--UPDATE
UPDATE Alumnos SET APELLIDO = 'Perez' WHERE NOMBRE = 'HUGO'
SELECT * FROM Alumnos;

--DELETE
DELETE Alumnos WHERE NOMBRE = 'HUGO'
SELECT * FROM Alumnos;


--DCL
--Creamos usuario y roles para el ejemplo
CREATE USER Joe without login;
CREATE ROLE Teachers;

ALTER ROLE Teachers ADD MEMBER Joe; 

--GRANT
GRANT SELECT ON  Alumnos TO Teachers;

--REVOKE
REVOKE SELECT ON  Alumnos TO Teachers;

--TCL
--COMMIT
BEGIN TRANSACTION UNO
    INSERT Alumnos(NOMBRE,APELLIDO,SEMESTRE) VALUES ('Juan','Perez',7);
COMMIT TRANSACTION UNO
SELECT * FROM Alumnos;

--ROLLBACK
BEGIN TRANSACTION DOS
      INSERT Alumnos(NOMBRE,APELLIDO,SEMESTRE) VALUES ('Pablo','Perez',1),('Pablo','Perez',1),('Pablo','Perez',1);
      SELECT * FROM Alumnos;
	ROLLBACK TRANSACTION DOS
COMMIT TRANSACTION DOS
SELECT * FROM Alumnos;

--SAVE POINT
BEGIN TRANSACTION TRES
	 SAVE TRANSACTION  SP1;
	UPDATE Alumnos SET APELLIDO = 'Alvarado' WHERE NOMBRE = 'Juan';
	SELECT * FROM Alumnos;
ROLLBACK TRANSACTION SP1

--DQL
--SELECT
SELECT * FROM Alumnos 
SELECT TOP 1 * FROM Alumnos;